version: '3.9'
services:

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./database:/var/lib/postgresql/data

  django:
    container_name: django
    build: ./app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./app/static:/opt/app/static:rw

  nginx:
    container_name: nginx
    image: nginx:1.23.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./app/static:/data/static:ro
    depends_on:
      - django
    ports:
      - "80:80"

  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7-arm64
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent ${ES_URL}  >/dev/null || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "9200:9200"

  etl:
    container_name: etl
    build: ./postgres_to_es
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      elastic:
        condition: service_healthy

  sqlite_to_pg:
    container_name: sqlite_to_pg
    build: ./sqlite_to_postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/opt/sqlite_to_postgres/.env:ro
    command: python3 main.py

volumes:
  database:
  static_volume:
  elasticsearch-data:
    driver: local